namespace SpriteKind {
    export const Hat = SpriteKind.create()
    export const Duck = SpriteKind.create()
    export const knighgt = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Hat, SpriteKind.knighgt, function (sprite, otherSprite) {
    sprite.say("Excuse Me!", 500)
    hat.setPosition(randint(15, 145), randint(15, 105))
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setPosition(randint(15, 145), randint(15, 105))
})
sprites.onOverlap(SpriteKind.Duck, SpriteKind.Hat, function (sprite, otherSprite) {
    sprite.say("Excuse Me!", 500)
    duckSprite.setPosition(randint(15, 145), randint(15, 105))
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Duck, function (sprite, otherSprite) {
    sprite.say("Excuse Me!", 500)
    mySprite.setPosition(randint(15, 145), randint(15, 105))
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Hat, function (sprite, otherSprite) {
    sprite.say("Excuse Me!", 500)
    mySprite.setPosition(randint(15, 145), randint(15, 105))
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.knighgt, function (sprite, otherSprite) {
    sprite.say("Excuse Me!", 500)
    mySprite.setPosition(randint(15, 145), randint(15, 105))
})
sprites.onOverlap(SpriteKind.Duck, SpriteKind.knighgt, function (sprite, otherSprite) {
    sprite.say("Excuse Me!", 500)
    duckSprite.setPosition(randint(15, 145), randint(15, 105))
})
let duckSprite: Sprite = null
let mySprite: Sprite = null
let hat: Sprite = null
hat = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .......4444444444...............
    .......4777777774...............
    .......4777777774...............
    .......4777777774...............
    .......4777777774...............
    .......4777777774...............
    .......4777777774...............
    .......444444444444444444.......
    .......666666666................
    .......666666666................
    .......646666666................
    .....66666666666................
    .....66666666666................
    .....66666666666................
    ......6666666666................
    ......6666666666................
    .......666666666................
    ......6666666666................
    ......6666666666................
    ......666666666.................
    ......666666666.................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Hat)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . 5 . . 5 . . 5 . . . . . . 
    . . . . 5 . 5 . 5 . . . . . . . 
    . . . . . 5 7 5 . . . . . . . . 
    . . . . 5 7 2 7 5 . . . . . . . 
    . . . . . 5 7 5 . . . . . . . . 
    . . . . . . 5 . . . . . . . . . 
    . . . . . . 1 . . . . . . . . . 
    . . 2 1 1 1 1 1 1 1 2 . . . . . 
    . . . . . . 1 . . . . . . . . . 
    . . . . . . 1 . . . . . . . . . 
    . . . . . . 1 . . . . . . . . . 
    . . . . . 1 . 1 . . . . . . . . 
    . . . . 7 . . . 7 . . . . . . . 
    . . . 7 . . . . . 7 . . . . . . 
    . . 2 2 . . . . . 2 2 . . . . . 
    `, SpriteKind.Player)
duckSprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . b 5 b . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b d 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b d 5 5 b 1 f f 5 4 4 c . . 
    b b d b 5 5 5 d f b 4 4 4 4 4 b 
    b d d c d 5 5 b 5 4 4 4 4 4 b . 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Duck)
let knightSprite = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.knighgt)
mySprite.setPosition(randint(15, 145), randint(15, 105))
duckSprite.setPosition(randint(15, 145), randint(15, 105))
knightSprite.setPosition(randint(15, 145), randint(15, 105))
hat.setPosition(35, 60)
